### ISSUE TITLE
POST should specify data within JSON to overwrite

### ISSUE THREAD

**Issue by VernitaJ** [marcopeg-dev/m07-cv-backend#17]
At the moment when using POST function, the entire JSON object is overwritten. The code should be changed to only change specifically provided information within the json object

**Comment by farooq029** [comment]
@VernitaJ  can you explain it .. I treid with postman what is get 

![Screenshot 2020-02-26 at 00 46 38](https://user-images.githubusercontent.com/34084867/75298041-b3b75600-5831-11ea-94ab-8838b9884d79.png)

**Comment by MayaPancake** [comment]
@VernitaJ  elaborate please and post screenshot if possible. Thanks

**Comment by marcopeg** [comment]
No, it's ok that the entire object gets overwritten for now.
It is a simplification for the sake of this first project.

The frontent will receive the full object, maybe change a few props, and then send it back for persistency

**Comment by marcopeg** [comment]
Making partial updates could be done in several different ways, the most efficient is a technique called "json patch" and I think is too early to bring it into this project.
